import { useCallback, useEffect, useMemo, useState, type ReactNode } from "react";
import { AlertTriangle, CheckCircle2, Database, Loader2, Plus, Radio, RefreshCw, ServerCrash, Trash2 } from "lucide-react";
import { dataApi, type CoverageRow, type SourceHealth, type StorageEntry, type WatchlistEntry } from "@/lib/dataApi";
import { cn } from "@/lib/utils";

type LoadState = { coverage: CoverageRow[]; sources: SourceHealth[]; storage: StorageEntry[]; totalBytes: number; softLimitBytes: number; watchlist: WatchlistEntry[] };
const EMPTY: LoadState = { coverage: [], sources: [], storage: [], totalBytes: 0, softLimitBytes: 10 * 1024 ** 3, watchlist: [] };

export function DataCenter() {
  const [state, setState] = useState<LoadState>(EMPTY);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [symbol, setSymbol] = useState("");
  const [adding, setAdding] = useState(false);
  const load = useCallback(async (mode: "initial" | "refresh" = "refresh") => {
    if (mode === "initial") setLoading(true); else setRefreshing(true);
    setError(null);
    try {
      const [coverage, sources, storage, watchlist] = await Promise.all([dataApi.coverage(), dataApi.sources(), dataApi.storage(), dataApi.watchlist()]);
      setState({ coverage: coverage.coverage, sources: sources.sources, storage: storage.entries, totalBytes: storage.total_bytes, softLimitBytes: storage.soft_limit_bytes, watchlist: watchlist.watchlist });
    } catch (err) { setError(err instanceof Error ? err.message : "数据中心暂不可用");
    } finally { setLoading(false); setRefreshing(false); }
  }, []);
  useEffect(() => { void load("initial"); }, [load]);
  const liveSources = useMemo(() => state.sources.filter((source) => source.last_status === "ok" && !source.circuit_open).length, [state.sources]);
  const staleSources = useMemo(() => state.sources.filter((source) => source.circuit_open || source.last_status === "failed").length, [state.sources]);
  const storagePercent = state.softLimitBytes ? Math.min(100, (state.totalBytes / state.softLimitBytes) * 100) : 0;
  const addWatchlist = async () => { const value = symbol.trim().toUpperCase(); if (!value) return; setAdding(true); try { await dataApi.addWatchlist(value); setSymbol(""); await load(); } catch (err) { setError(err instanceof Error ? err.message : "无法添加自选标的"); } finally { setAdding(false); } };
  const removeWatchlist = async (target: string) => { try { await dataApi.removeWatchlist(target); await load(); } catch (err) { setError(err instanceof Error ? err.message : "无法移除自选标的"); } };
  const prewarm = async () => { setRefreshing(true); setError(null); try { await dataApi.prewarm("premarket"); await load(); } catch (err) { setError(err instanceof Error ? err.message : "预热未完成"); } finally { setRefreshing(false); } };
  return <div className="min-h-screen p-4 sm:p-6 lg:p-8"><div className="mx-auto flex w-full max-w-6xl flex-col gap-5">
    <header className="flex flex-col gap-3 border-b pb-5 sm:flex-row sm:items-end sm:justify-between"><div><div className="inline-flex items-center gap-2 rounded-md border px-2.5 py-1 text-xs font-medium text-muted-foreground"><Database className="h-3.5 w-3.5" />统一数据层</div><h1 className="mt-3 text-3xl font-bold tracking-tight">数据中心</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">行情、新闻与研报的缓存覆盖、数据源健康度和预热状态。市场缓存与 Loader Cache 保持物理隔离。</p></div><div className="flex gap-2"><button type="button" onClick={prewarm} disabled={refreshing} className="inline-flex items-center justify-center gap-2 rounded-md bg-primary px-3 py-2 text-sm font-medium text-primary-foreground disabled:opacity-50">{refreshing ? <Loader2 className="h-4 w-4 animate-spin" /> : <Radio className="h-4 w-4" />}立即预热</button><button type="button" onClick={() => void load()} disabled={refreshing} className="inline-flex items-center justify-center gap-2 rounded-md border px-3 py-2 text-sm font-medium hover:bg-muted disabled:opacity-50"><RefreshCw className={cn("h-4 w-4", refreshing && "animate-spin")} />刷新</button></div></header>
    {error ? <section role="alert" className="rounded-md border border-amber-500/30 bg-amber-500/5 p-4 text-sm text-amber-700 dark:text-amber-300"><AlertTriangle className="mr-2 inline h-4 w-4" />{error}</section> : null}
    {loading ? <div className="grid gap-3 sm:grid-cols-2 2xl:grid-cols-4">{[1, 2, 3, 4].map((key) => <div key={key} className="h-28 animate-pulse rounded-md border bg-muted/40" />)}</div> : <section className="grid gap-3 sm:grid-cols-2 2xl:grid-cols-4" aria-label="数据层状态摘要"><Summary title="实时数据源" value={`${liveSources}/${state.sources.length || 0}`} description="两源校核；冲突时请求第三源" tone={liveSources ? "good" : "muted"} icon={CheckCircle2} /><Summary title="降级/熔断" value={String(staleSources)} description="失败 3 次后冷却 5 分钟" tone={staleSources ? "warn" : "good"} icon={staleSources ? AlertTriangle : ServerCrash} /><Summary title="K 线覆盖" value={String(state.coverage.length)} description="按标的、周期、复权和来源" tone="muted" icon={Database} /><Summary title="存储使用" value={formatBytes(state.totalBytes)} description={`${storagePercent.toFixed(1)}% / ${formatBytes(state.softLimitBytes)}`} tone={storagePercent >= 90 ? "warn" : "muted"} icon={Database} /></section>}
    <section className="rounded-md border p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold">持仓与手动自选预热</h2><p className="mt-1 text-sm text-muted-foreground">仅持仓和这里的手动自选会进入盘前/盘中预热；Agent 只能建议，不能自行加入。</p></div><div className="flex gap-2"><input aria-label="自选标的代码" value={symbol} onChange={(event) => setSymbol(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") void addWatchlist(); }} placeholder="例如 510300.SH" className="w-40 rounded-md border bg-background px-3 py-2 text-sm" /><button type="button" onClick={() => void addWatchlist()} disabled={adding || !symbol.trim()} className="inline-flex items-center gap-1 rounded-md border px-3 py-2 text-sm hover:bg-muted disabled:opacity-50">{adding ? <Loader2 className="h-4 w-4 animate-spin" /> : <Plus className="h-4 w-4" />}添加</button></div></div><div className="mt-4 flex flex-wrap gap-2">{state.watchlist.length ? state.watchlist.map((item) => <span key={item.symbol} className="inline-flex items-center gap-1 rounded-full border bg-muted/40 px-2.5 py-1 text-sm"><span className="font-mono">{item.symbol}</span><button type="button" aria-label={`移除 ${item.symbol}`} onClick={() => void removeWatchlist(item.symbol)} className="rounded p-0.5 text-muted-foreground hover:bg-background hover:text-foreground"><Trash2 className="h-3.5 w-3.5" /></button></span>) : <span className="text-sm text-muted-foreground">尚无手动自选。</span>}</div></section>
    <section className="grid gap-5 xl:grid-cols-2"><TableCard title="K 线缓存覆盖" description="历史已结算数据缓存优先，仅补缺口；当前尾部实时优先。"><CoverageTable rows={state.coverage} /></TableCard><TableCard title="数据源健康度" description="显示最近状态、延迟、连续失败和熔断。"><SourcesTable rows={state.sources} /></TableCard></section>
    <section className="rounded-md border p-4"><h2 className="font-semibold">存储与保留</h2><p className="mt-1 text-sm text-muted-foreground">9 GB 开始驱逐，10 GB 软上限；受保护标的保留更长的日线历史。新闻正文 180 天，研报正文 5 年。</p><div className="mt-3 h-2 overflow-hidden rounded-full bg-muted" aria-label={`存储使用 ${storagePercent.toFixed(1)}%`}><div className={cn("h-full rounded-full", storagePercent >= 90 ? "bg-amber-500" : "bg-primary")} style={{ width: `${storagePercent}%` }} /></div><div className="mt-4 grid gap-2 text-sm sm:grid-cols-3">{state.storage.map((entry) => <div key={entry.kind} className="rounded-md border p-3"><div className="font-medium">{entry.kind}</div><div className="mt-1 text-muted-foreground">{formatBytes(entry.bytes)}</div></div>)}</div></section>
  </div></div>;
}
function Summary({ title, value, description, tone, icon: Icon }: { title: string; value: string; description: string; tone: "good" | "warn" | "muted"; icon: typeof Database }) { return <article className="rounded-md border p-4"><div className="flex items-center justify-between gap-3"><span className="text-xs font-medium uppercase text-muted-foreground">{title}</span><Icon className={cn("h-4 w-4", tone === "good" && "text-emerald-600", tone === "warn" && "text-amber-600", tone === "muted" && "text-muted-foreground")} /></div><div className="mt-3 text-2xl font-semibold">{value}</div><p className="mt-1 text-xs text-muted-foreground">{description}</p></article>; }
function TableCard({ title, description, children }: { title: string; description: string; children: ReactNode }) { return <section className="rounded-md border p-4"><h2 className="font-semibold">{title}</h2><p className="mt-1 text-sm text-muted-foreground">{description}</p><div className="mt-4 overflow-x-auto">{children}</div></section>; }
function CoverageTable({ rows }: { rows: CoverageRow[] }) { if (!rows.length) return <p className="py-5 text-sm text-muted-foreground">暂无 K 线缓存；首次数据请求或预热后会显示覆盖范围。</p>; return <table className="w-full min-w-[530px] text-left text-sm"><thead className="border-b text-xs text-muted-foreground"><tr><th className="pb-2 font-medium">标的</th><th className="pb-2 font-medium">周期</th><th className="pb-2 font-medium">复权</th><th className="pb-2 font-medium">范围</th><th className="pb-2 font-medium">来源</th></tr></thead><tbody>{rows.map((row) => <tr key={`${row.symbol}-${row.actual_source}-${row.interval}-${row.actual_adjustment}`} className="border-b last:border-0"><td className="py-2 font-mono">{row.symbol}</td><td className="py-2">{row.interval}</td><td className="py-2">{row.actual_adjustment}</td><td className="py-2 text-xs text-muted-foreground">{shortDate(row.min_bar_time)} → {shortDate(row.max_bar_time)}</td><td className="py-2">{row.actual_source}</td></tr>)}</tbody></table>; }
function SourcesTable({ rows }: { rows: SourceHealth[] }) { if (!rows.length) return <p className="py-5 text-sm text-muted-foreground">尚无数据源请求记录。</p>; return <table className="w-full min-w-[480px] text-left text-sm"><thead className="border-b text-xs text-muted-foreground"><tr><th className="pb-2 font-medium">来源</th><th className="pb-2 font-medium">状态</th><th className="pb-2 font-medium">延迟</th><th className="pb-2 font-medium">连续失败</th></tr></thead><tbody>{rows.map((row) => <tr key={row.source} className="border-b last:border-0"><td className="py-2">{row.source}</td><td className="py-2"><span className={cn("rounded-full px-2 py-0.5 text-xs", row.circuit_open ? "bg-amber-500/15 text-amber-700 dark:text-amber-300" : row.last_status === "ok" ? "bg-emerald-500/15 text-emerald-700 dark:text-emerald-300" : "bg-muted text-muted-foreground")}>{row.circuit_open ? "熔断冷却" : row.last_status === "ok" ? "可用" : "失败"}</span></td><td className="py-2">{row.last_latency_ms == null ? "—" : `${row.last_latency_ms.toFixed(0)} ms`}</td><td className="py-2">{row.consecutive_failures}</td></tr>)}</tbody></table>; }
function shortDate(value: string): string { return value ? value.replace("T", " ").slice(0, 16) : "—"; }
function formatBytes(bytes: number): string { if (bytes < 1024) return `${bytes} B`; const units = ["KB", "MB", "GB", "TB"]; let value = bytes / 1024; let index = 0; while (value >= 1024 && index < units.length - 1) { value /= 1024; index += 1; } return `${value.toFixed(value >= 10 ? 0 : 1)} ${units[index]}`; }
